# Generated by Django 5.0.7 on 2024-08-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agregarbase',
            options={'ordering': ['created_at'], 'verbose_name': 'Base', 'verbose_name_plural': 'Historial de Bases'},
        ),
        migrations.AlterModelOptions(
            name='agregargasto',
            options={'ordering': ['created_at'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['payment_date'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='couta_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='monto_mas_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
