# Generated by Django 5.0.7 on 2024-07-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamosapp', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='payment_amount',
        ),
    ]
