# Generated by Django 5.0.7 on 2024-07-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamosapp', '0003_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgregarBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_base', models.CharField(max_length=200)),
                ('monto_base', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AgregarGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_gasto', models.CharField(max_length=200)),
                ('monto_gasto', models.IntegerField()),
            ],
        ),
    ]
