# Generated by Django 5.0.7 on 2024-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamosapp', '0004_agregarbase_agregargasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregarbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agregargasto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
