# Generated by Django 5.0.7 on 2024-08-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamosapp', '0006_alter_payment_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='couta_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='monto_mas_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
